config/routes.rb
Rails.application.routes.draw do

  resources :employees
  resources :tasks do
  	resources :items
  end
  resources :articles do
  	resources :comments
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments , dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :items , dependent: :destroy
  accepts_nested_attributes_for :items,  :reject_if => :all_blank, :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
/	http_basic_authenticate_with name: "dhh", password: "secret",
	except: [:index, :show]/

	#List all Articles
	def index
		@articles = Article.all
	end

	#Show an Article (/::id)
	def show
		@article = Article.find(params[ :id])
	end

	#Add new Article
	def new
		@article = Article.new
	end

	#Edit an Article
	def edit
		@article = Article.find(params[:id])  
	end

	#Create an Article
	def create
	  @article = Article.new(article_params)
	 
	  if @article.save
	  	redirect_to @article
	  else
	  	render 'new'
	  end
	end

	#Update an Article
	def update
		@article = Article.find(params[:id])  
		
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	#Deletes an Article
	def destroy
		@article = Article.find(params[:id])  
		@article.destroy

		redirect_to articles_path
	end

	#Private Params
	private 
		def article_params
			params.require(:article).permit(:title,:text)
		end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
/	http_basic_authenticate_with name: "dhh", password: "secret",
	except: [:index, :show]/

  def create
    @article = Article.find(params[ :article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path( @article)
  end
  def destroy
    @article = Article.find(params[ :article_id])
    @comment = @article.comments.find(params[ :id])
    @comment.destroy
    redirect_to article_path( @article)
  end
  private
    def comment_params
      params.require( :comment).permit(:commenter, :body)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.fetch(:employee, {})
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @task = Task.find(params[ :task_id])
    @item = @task.items.create(item_params)
    redirect_to task_path( @task)
  end
  def destroy
    @task = Task.find(params[ :task_id])
    @item = @task.items.find(params[ :id])
    @item.destroy
    redirect_to task_path( @task)
  end
  private
    def item_params
      params.require( :item).permit(:title)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :index, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/task_items_helper.rb
module TaskItemsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation" >
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="blog-app">
    <div class="blog-header">
       <div class="title">
            <h1>All Articles</h1>
       </div>
        <div class="blog-actions">
            <%= link_to 'New article', new_article_path %>
        </div>
    </div>
    <div class="blog-content">
        <% @articles.each do |article| %>
            <div class="article"> 
                <div class="article-title">
                    <%= article.title %>
                </div>
                <div class="article-content">
                    <%= article.text %>
              <%= link_to 'Show', article_path(article) %>
              <%= link_to 'Edit', edit_article_path(article) %>
              <%= link_to 'Destroy', article_path(article),
                       method: :delete,
                      data: { confirm: 'Are you sure?' } %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path( @article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
  <%= link_to 'Destroy Comment' , [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ]) do |form|%>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/items/_form.html.erb
<%= form_with(model: [ @task, @task.items.build ]) do |form|%>
  <p>
    <%= form.label :Title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/items/_item.html.erb
 <div class="item-container">
	 <div class="title">
	 	- <%= item.title %>
	 </div>
	<div class="actions">
		<%= link_to 'Delete' , [item.task, item],
		               method: :delete,
		               data: { confirm: 'Are you sure?' } %>	
	</div> 	
</div>
  

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="controls">
  <%= form.text_field :title %>
</div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>
<%= link_to 'New Task', new_task_path %>

<div id="sort-task" class="task-container">
  
    <% @tasks.each do |task| %>
    <div id="drag" class="task ui-draggable">
      <div class="task-header">
        <h3><%= task.title %></h3>
        <ul>
           <% task.items.each do |items| %>
            <li> <%= items.title %></li>
          <% end %>
        </ul>
      </div>
      <div class="task-body">
      </div>
      <div class="task-foo">
        <%= link_to 'Show', task %>
        <%= link_to 'Edit', edit_task_path(task) %>
        <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>

    <% end %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<div class="task-show">
	<div class="task-title">
		<h1>  <%= @task.title %> - Task Info</h1>
	</div>
	<div class="task-info">
		<div class="task-items">
			<div class="items-actions">
				<%= render 'items/form' %>
			</div>
			<div class="items">
				<%= render @task.items %>
			</div>
		</div>
	</div>
	<div class="task-config">
		<%= link_to 'Edit', edit_task_path(@task) %> |
		<%= link_to 'Back', tasks_path %>	
	</div>
</div>